### ISSUE TITLE
How to download games on Fox Go

### ISSUE THREAD

**Issue by Dreamkeeper66666** [CamWagner/go-dataset#1]
Thanks for your dataset! I am wondering how I can download some specific games like Fine Art's games on Fox Go. Is there a parser for this? Thanks a lot!

**Comment by featurecat** [comment]
Hmm for some reason I couldn't decipher the network data when I tried to investigate this, sorry. Maybe Tencent started encrypting the Foxgo client's data.

**Comment by Dreamkeeper66666** [comment]
Okay! Thanks! I just happened to see your foxy-game-scraper. The url in your script worked. How did you find it? @featurecat

**Comment by yenw** [comment]
@Dreamkeeper66666 
@featurecat 
```python
#!/bin/python
# coding=utf-8

import urllib
import urllib2
import json
import codecs
import time
import sys

def game_list(lastCode):
    values = {
    "type": 4,
    "lastCode": lastCode,
    "FindUserName": "57ud6Im65oyH5a", #FineArt Teach A
    "uid": 17231185, #FineArt Teach A
    
    "RelationTag": 0}
    data = urllib.urlencode(values)
    url = "http://happyapp.huanle.qq.com/cgi-bin/CommonMobileCGI/TXWQFetchChessList"
    request = urllib2.Request(url, data)
    response = urllib2.urlopen(request)
    chesslist = json.loads(response.read())['chesslist']

    chessid = []
    fn = []
    for d in chesslist:
        chessid.append(d['chessid'])
        starttime = d['starttime'].split(' ')[0].replace('-', '.')
        id = d['chessid'][10:]
        blackenname = d['blackenname']
        whiteenname = d['whiteenname']
        fn.append(starttime + ' ' + blackenname + ' VS ' + whiteenname + ' (' + id + ')' + '.SGF')
    return chessid, fn

def download_sgf(cid, fn):
    values = {
    "chessid": cid
    }
    data = urllib.urlencode(values)
    url = "http://happyapp.huanle.qq.com/cgi-bin/CommonMobileCGI/TXWQFetchChess"
    sgf = ""
    for i in range(10):
        try:
            request = urllib2.Request(url, data)
            response = urllib2.urlopen(request)
            sgf = json.loads(response.read())['chess']
            break
        except Exception as e:
            if i == 9:
                print e
                sys.exit(1)

    f = codecs.open(fn, 'w', 'utf-8')
    f.write(sgf)
    f.close()

def download_all_user_sgf():
    chessid, fn = game_list("")
    idx = 0
    for i in range(len(chessid)):
        download_sgf(chessid[i], fn[i])
        print i + 1, fn[i]
        time.sleep(0.5)

    while True:
        lastCode = chessid[-1]
        idx += len(chessid)
        chessid, fn = game_list(lastCode)
        if len(chessid) == 0:
            break

        for i in range(len(chessid)):
            download_sgf(chessid[i], fn[i])
            print i + idx + 1, fn[i]
            time.sleep(0.5)

download_all_user_sgf()
```

**Comment by featurecat** [comment]
Ah thanks, how did you find FineArt's uid? I tried last night but failed to figure it out.

Originally for the url I found it by using netshark. When I tried it last night I couldn't figure it out again, though. I'm not sure if it's because Foxgo changed or because I forgot how to use netshark. Thanks Yenw!

**Comment by Dreamkeeper66666** [comment]
Thanks for yenw's  script. @yenw I also happened to find out FineArt's uid by letting LastCode be equal to one of its previous game's chessid plus 1 or something and type be equal to 3 . And the game info with its uid showed up, lol. To get one of FineArt's chessid, we can search it on Fox Go Client.  Maybe this method is kind of dumb haha @featurecat

**Comment by yenw** [comment]
I use some traffic analysis software (e.g. `wireshark`, `charles`, `burpsuite`) to get `url`, `FindUserName` and `uid`.
I didn't research it deeply, so I don't know if there are other simple ways to get `uid`.

**Comment by Dreamkeeper66666** [comment]
> I use some traffic analysis software (e.g. `wireshark`, `charles`, `burpsuite`) to get `url`, `FindUserName` and `uid`.
> I didn't research it deeply, so I don't know if there are other simple ways to get `uid`.

I also used wireshark, but I didn't really know how to analyze the tcp stream and totally have no idea how to decypt it. So did you just decrypt it by yourself or using some tools?

**Comment by yenw** [comment]
Perhaps as featurecat said, foxwq updated their program.
Maybe like I download the kifu of TYGEM, you can download kifu through a TCP bot.

A long time ago, I discovered that some data is transmitted using TCP only, 
and its format is protobuf.

**Comment by Dreamkeeper66666** [comment]
Exactly, thanks again! It really helped me a lot. By the way, I just found that "FindUserName" is not a parameter anymore since there is no FindUserName in the response and it returns searchkey:0 instead. It doesn't make any difference if you get rid of FindUserName. So I guess it's important to figure out what the searchkey is.

**Comment by siasio** [comment]
> @Dreamkeeper66666 @featurecat
> 
> ```python
> #!/bin/python
> # coding=utf-8
> 
> import urllib
> import urllib2
> import json
> import codecs
> import time
> import sys
> 
> def game_list(lastCode):
>     values = {
>     "type": 4,
>     "lastCode": lastCode,
>     "FindUserName": "57ud6Im65oyH5a", #FineArt Teach A
>     "uid": 17231185, #FineArt Teach A
>     
>     "RelationTag": 0}
>     data = urllib.urlencode(values)
>     url = "http://happyapp.huanle.qq.com/cgi-bin/CommonMobileCGI/TXWQFetchChessList"
>     request = urllib2.Request(url, data)
>     response = urllib2.urlopen(request)
>     chesslist = json.loads(response.read())['chesslist']
> 
>     chessid = []
>     fn = []
>     for d in chesslist:
>         chessid.append(d['chessid'])
>         starttime = d['starttime'].split(' ')[0].replace('-', '.')
>         id = d['chessid'][10:]
>         blackenname = d['blackenname']
>         whiteenname = d['whiteenname']
>         fn.append(starttime + ' ' + blackenname + ' VS ' + whiteenname + ' (' + id + ')' + '.SGF')
>     return chessid, fn
> 
> def download_sgf(cid, fn):
>     values = {
>     "chessid": cid
>     }
>     data = urllib.urlencode(values)
>     url = "http://happyapp.huanle.qq.com/cgi-bin/CommonMobileCGI/TXWQFetchChess"
>     sgf = ""
>     for i in range(10):
>         try:
>             request = urllib2.Request(url, data)
>             response = urllib2.urlopen(request)
>             sgf = json.loads(response.read())['chess']
>             break
>         except Exception as e:
>             if i == 9:
>                 print e
>                 sys.exit(1)
> 
>     f = codecs.open(fn, 'w', 'utf-8')
>     f.write(sgf)
>     f.close()
> 
> def download_all_user_sgf():
>     chessid, fn = game_list("")
>     idx = 0
>     for i in range(len(chessid)):
>         download_sgf(chessid[i], fn[i])
>         print i + 1, fn[i]
>         time.sleep(0.5)
> 
>     while True:
>         lastCode = chessid[-1]
>         idx += len(chessid)
>         chessid, fn = game_list(lastCode)
>         if len(chessid) == 0:
>             break
> 
>         for i in range(len(chessid)):
>             download_sgf(chessid[i], fn[i])
>             print i + idx + 1, fn[i]
>             time.sleep(0.5)
> 
> download_all_user_sgf()
> ```

Thanks for this code! Works very well. However, I can see only games until November 2022. Perhaps, Fox moved hosting to another website. Does anyone know where to find recent Fox games?

**Comment by psygo** [comment]
Does anyone know how to get the games of a specific day, ordered by strength? I've also asked about [this on Reddit (r/baduk)](https://www.reddit.com/r/baduk/comments/1cydo1u/does_fox_weiqi_have_api_endpoints_for_listing_the/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button).

**Comment by siasio** [comment]
Not sure about games of a specific day, but I wanted to add one more thing which I found out after a search on the Web:

A few years ago [Fox Server](https://www.foxwq.com/) was cooperating with Tencent. But then, they split, and Tencent created their [own server](https://txwq.qq.com/). The hosting referred to in this repo is still used by the Tencent Weiqi server for the recent games.

For the sake of programmatic game downloading, we could start playing on the latter server ;) Though I'm not sure if it's possible to create an account there without WeChat.
